Numix-Cinnamon-Semi-Transparent
linuxmint/cinnamon-spices-themes pull request #672
Opened 2020-10-26 16:03 UTC by bomdia

Updated README
Show current open application on windows list

2020-11-06 21:39 UTC, claudiux requested changes

2020-11-06 21:39 UTC, claudiux commented on Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/changePrimaryColor.py
> +    return str[str.find(start)+len(start):str.rfind(end)].strip()
`str` is a reserved word.

```python
def between(s,start,end):
    return s[s.find(start)+len(start):s.rfind(end)].strip()
```

2020-11-06 21:41 UTC, claudiux requested changes

2020-11-06 21:41 UTC, claudiux commented on Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/changePrimaryColor.py
> +
Line 39: suppress all spaces.

2020-11-07 23:53 UTC, bomdia commented
ok i've deleted the wip script as is irrilevant for theme now, can you merge this now @claudiux

2020-11-08 08:09 UTC, merged