Add Windows 10 Dark
linuxmint/cinnamon-spices-themes pull request #751
Opened 2023-06-05 13:22 UTC by Elbullazul

Add dark version of Windows 10

2023-07-03 05:30 UTC, rcalixte requested changes

2023-07-03 05:30 UTC, rcalixte commented on Windows-10-Dark/Windows-10-Dark
I don't believe this will work as a submodule. Can you replace the submodule with the theme files?

2023-07-05 16:07 UTC, Elbullazul commented on Windows-10-Dark/Windows-10-Dark
https://github.com/linuxmint/cinnamon-spices-themes/pull/751/commits/2f1173deb7ee082bcde62603251e9086d33c37c1 adds the required files

2023-07-05 18:08 UTC, rcalixte approved these changes

2023-07-05 18:08 UTC, merged